name: 'Trello Staging Sync'
description: 'Syncs the environment to staging when the branch attached to a card is deployed to staging'
inputs:
  trello_key:
    description: 'key from Trello (https://trello.com/app-key)'
    required: true
  trello_token:
    description: 'token from Trello (https://trello.com/app-key)'
    required: true
  github_token:
    description: 'token from Github (use secrets.GITHUB_TOKEN)'
    required: true
  trello_board_id:
    description: 'Id of the board to sync with. Can be found in the URL of the main board: (ex. trello.com/b/{ID}/your-board-name)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
